<a href="https://colab.research.google.com/github/biswal-prem-5677/Coding-Journey/blob/main/languages/python/libraries/numpy/experiment_numpy_matrix_operations_and_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basic Matrix Operations in NumPy**

(a) Matrix Creation

In [12]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


(b) Addition

In [2]:
C = A + B
print(C)

[[ 6  8]
 [10 12]]


(c) Subtraction

In [3]:
C = A - B
print(C)

[[-4 -4]
 [-4 -4]]


(d) Element-wise Multiplication

In [4]:
C = A * B
print(C)

[[ 5 12]
 [21 32]]


(e) Matrix Multiplication

In [5]:
C = A @ B
# OR
C = np.dot(A, B)

print(C)

[[19 22]
 [43 50]]


(f) Transpose

In [6]:
print(A.T)

[[1 3]
 [2 4]]


(g) Inverse

In [7]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


# **Broadcasting in NumPy**

Scalar + Matrix

In [8]:
A = np.array([[1, 2],
              [3, 4]])

B = A + 10
print(B)

[[11 12]
 [13 14]]


Vector + Matrix (Row-wise)

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

C = A + B
print(C)

[[11 22 33]
 [14 25 36]]


Column Broadcasting

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10],
              [20]])

C = A + B
print(C)

[[11 12 13]
 [24 25 26]]


# **Real ML Use Case**

In [11]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

mean = np.mean(X, axis=0)
X_norm = X - mean   # Broadcasting

print(X_norm)

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
