<a href="https://colab.research.google.com/github/biswal-prem-5677/Coding-Journey/blob/main/ai/02_machine_learning/supervised/classification/experiment_classification_algorithms_comparison_on_iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# Compare Major ML Classification Algorithms
# ============================================================

import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Classification Algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

# Metrics
from sklearn.metrics import accuracy_score

# ============================================================
# Load Dataset
# ============================================================

iris = load_iris()

X = iris.data
y = iris.target

# ============================================================
# Train-Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ============================================================
# Feature Scaling
# ============================================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ============================================================
# Models
# ============================================================

models = {

    "Logistic Regression":
        LogisticRegression(),

    "K-Nearest Neighbors":
        KNeighborsClassifier(),

    "Decision Tree":
        DecisionTreeClassifier(),

    "Random Forest":
        RandomForestClassifier(),

    "Support Vector Machine":
        SVC(),

    "Naive Bayes":
        GaussianNB()
}

# ============================================================
# Train + Predict + Evaluate
# ============================================================

results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Store result
    results.append([name, accuracy])

# ============================================================
# Display Results
# ============================================================

results_df = pd.DataFrame(
    results,
    columns=["Algorithm", "Accuracy"]
)

print(results_df)

                Algorithm  Accuracy
0     Logistic Regression       1.0
1     K-Nearest Neighbors       1.0
2           Decision Tree       1.0
3           Random Forest       1.0
4  Support Vector Machine       1.0
5             Naive Bayes       1.0


In [2]:
# ============================================================
# Logistic Regression
# ============================================================

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred))

Logistic Regression Accuracy: 1.0


In [3]:
# ============================================================
# K-Nearest Neighbors (KNN)
# ============================================================

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("KNN Accuracy:",
      accuracy_score(y_test, y_pred))

KNN Accuracy: 1.0


In [4]:
# ============================================================
# Decision Tree
# ============================================================

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Decision Tree Accuracy:",
      accuracy_score(y_test, y_pred))

Decision Tree Accuracy: 1.0


In [5]:
# ============================================================
# Random Forest
# ============================================================

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, y_pred))

Random Forest Accuracy: 1.0


In [6]:
# ============================================================
# Support Vector Machine (SVM)
# ============================================================

from sklearn.svm import SVC

model = SVC(kernel="linear")

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("SVM Accuracy:",
      accuracy_score(y_test, y_pred))

SVM Accuracy: 0.9666666666666667


In [7]:
# ============================================================
# Naive Bayes
# ============================================================

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Naive Bayes Accuracy:",
      accuracy_score(y_test, y_pred))

Naive Bayes Accuracy: 1.0


In [8]:
# ============================================================
# Confusion Matrix Example
# ============================================================

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [9]:
# ============================================================
# Classification Report
# ============================================================

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

